name: TemplarWar
main: me.Duppy.TemplarWar.Main.Main
author: DuppyIsCool
version: 1.0
description: Faction v Faction plugin
commands:
    teams:
        description: Base command used for all team related commands.
        usage: /<command>
        aliases: [team,t]