name: TeamWar
main: me.Duppy.TemplarWar.Main.Main
author: DuppyIsCool
version: 1.0
api-version: 1.15
description: Teams and guilds plugin
depend: [Vault]
commands:
    teams:
        description: Base command used for all team related commands.
        usage: /<command>
        aliases: [team,t]
    guilds:
        description: Base command used for all guild related commands.
        usage: /<command>
        aliases: [guild,g]
    